In [1]:
import numpy as np
import scipy.spatial

########################################################################
#########  Data Generating Functions ###################################
########################################################################
def generate_sensors(k = 7, d = 2):
	"""
	Generate sensor locations. 
	Input:
	k: The number of sensors.
	d: The spatial dimension.
	Output:
	sensor_loc: k * d numpy array.
	"""
	sensor_loc = 100*np.random.randn(k,d)
	return sensor_loc

def generate_data_given_location(sensor_loc, obj_loc, k = 7, d = 2):
	"""
	Generate the distance measurements given location of a single object and sensor. 

	Input:
	obj_loc: 1 * d numpy array. Location of object
	sensor_loc: k * d numpy array. Location of sensor. 
	k: The number of sensors.
	d: The spatial dimension. 

	Output: 
	distance: 1 * k numpy array. The distance between object and 
	the k sensors. 
	"""
	assert k, d == sensor_loc.shape 
	 
	distance = scipy.spatial.distance.cdist(obj_loc, 
					   sensor_loc, 
					   metric='euclidean')
	distance += np.random.randn(1, k)  
	return obj_loc, distance

##################################################################
# Starter code for Part (b)
##################################################################
import math
def compute_gradient(distance, loc, sensor_loc):
    '''
    This function computes the gradient at a particular point
    '''
    total_x = 0
    total_y = 0
    x1 = loc[0]
    y1 = loc[1]
    
    for i in range(7):
        ai = sensor_loc[i][0]
        bi = sensor_loc[i][1]
        di = distance[i]
        total_x += 2 * (math.sqrt((ai - x1)**2 + (bi -y1)**2) - di) * (ai - x1)/math.sqrt((ai - x1)**2 + (bi -y1)**2)
    for i in range(7):
        ai = sensor_loc[i][0]
        bi = sensor_loc[i][1]
        di = distance[i]
        total_y += 2 * (math.sqrt((ai - x1)**2 + (bi -y1)**2) - di) * (bi - y1)/math.sqrt((ai - x1)**2 + (bi -y1)**2)
    gradient = np.array([total_x,total_y]) * -1
    return gradient



def compute_update(distance, current_loc, sensor_loc, step_count, step_size):
    """Computes the new point after the update at x."""
    return current_loc - step_size(step_count) * compute_gradient(distance, current_loc, sensor_loc)


def compute_updates(distance, p, sensor_loc, total_step_count, step_size):
    """Computes several updates towards the minimum of ||Ax-b|| from p.

    Params:
        b: in the equation ||Ax-b||
        p: initialization point
        total_step_count: number of iterations to calculate
        step_size: function A, b,for determining the step size at step i
    """
    positions = [np.array(p)]
    for k in range(total_step_count):
        positions.append(compute_update(distance,  positions[-1], sensor_loc, k, step_size))
    return np.array(positions)






# Sensor locations. 

num_gd_replicates = 100

obj_locs = [[[i,i]] for i in np.arange(0,1000,100)]  
np.random.seed(100)
total_step_count = 1000 
step_size = lambda i: .05
est_pos = [list()] * 10

for k, obj_loc in enumerate(obj_locs):
    for j in range(num_gd_replicates):
        sensor_loc = generate_sensors()
        obj_loc, distance = generate_data_given_location(sensor_loc, obj_loc, k = 7, d = 2)
        single_distance = distance[0]
        initial_position = (obj_loc[0][0]+1)*np.random.randn(2)
        positions = compute_updates(single_distance, initial_position, sensor_loc, total_step_count, step_size)
        print(positions[-1])
#for pos in est_pos:
#    print(pos)

[ 0.44748703  0.54216888]
[-0.14616641  0.60797133]
[-0.21298272  0.90233503]
[ 0.08017511  0.02559112]
[-0.10868392 -0.84941466]
[-0.33599844 -0.46239289]
[ 0.15313916 -1.08768376]
[ 0.00892425 -0.33778425]
[ 0.40868145  0.08012346]
[ 1.00013477  0.88232316]
[ 0.80845909  0.56578818]
[ 0.67861578 -0.05978386]
[ 0.64847117  0.23736313]
[ 0.12519692 -0.54403722]
[ 0.80937434  0.45501578]
[ 0.34282071  0.00966886]
[-0.80487288 -0.08655978]
[ 0.28196528  0.05501552]
[-0.66854096  0.54806346]
[-0.44718384 -0.12106312]
[ 0.59519612  0.39409766]
[-0.03306278 -0.96851503]
[ 0.84659593 -0.37943592]
[ 0.16301731  0.79401245]
[-0.86885604 -0.14982673]
[ 0.5516577   0.68957669]
[-0.48846646  0.54917179]
[-0.1654791   0.30380218]
[ 0.95194801 -0.55976121]
[ 0.57136694  0.22375164]
[-0.18068397 -0.08876045]
[ 0.59164976  1.44099083]
[-0.21742651  0.43303701]
[-0.19946485 -0.6042309 ]
[-0.56387881  0.12138806]
[ 0.74480371 -0.84980905]
[ 0.51725007  0.17307299]
[ 0.19601431 -0.58396922]
[-0.43998158

[ 200.0704739   199.65931106]
[ 198.01936041  201.55903736]
[ 199.82044841  200.92099508]
[ 200.36439195  198.87893529]
[ -15.99714608 -234.02933517]
[ 200.40326734  199.54511208]
[ 199.18364211  201.21072515]
[-364.98986217  -82.24279657]
[ 200.39773938  199.27071616]
[ 199.6096547   200.32346672]
[ 201.21722408  199.66919377]
[ 298.43736935  301.89520821]
[ 300.28760055  298.84518959]
[ 117.91609162 -358.90671007]
[ 299.82429869  299.91094593]
[ 298.54052633  300.1576411 ]
[ 300.00504008  299.45007469]
[ 301.74921424  297.80490716]
[ 299.20236805  301.49958063]
[ 299.39240252  300.47721439]
[ 304.25633943  296.20250003]
[ 303.21767248  297.54028962]
[ 297.94891738  301.35022912]
[ 299.40680263  301.59811443]
[ 300.49089286  299.35927032]
[ 298.91168631  301.07758832]
[ 301.06465999  298.43708311]
[ 300.37151553  299.75394009]
[ 301.03081692  298.65345438]
[ 298.32088237  302.33625822]
[ 301.66915328  298.55272468]
[ 301.57646699  296.81214525]
[ 298.17483672  301.72443116]
[ 300.7335

[ 499.9514715   500.50456627]
[ 501.14327293  498.87419819]
[ 500.86069913  498.99777629]
[ 519.69588113  475.67348189]
[ 509.53391653  490.35590318]
[ 484.52163374  513.99115034]
[ 487.26570331  511.57744359]
[ 500.10353787  500.19611216]
[ 500.1058325   500.89470762]
[ 502.2421779   497.77511373]
[ 501.2187154   499.23150821]
[ 546.76978984  447.7971871 ]
[-522.20063531 -423.1067544 ]
[-124.26860702  653.12647308]
[ 499.24922458  500.68302085]
[ 499.7177199   499.31725229]
[ 487.22246044  512.38485831]
[ 500.4318992   499.16428419]
[ 498.03573741  501.25170045]
[ 494.90183052  503.87513986]
[ 497.63492997  502.65458284]
[ 496.25337544  503.0184107 ]
[ 504.10011418  496.49420407]
[ 498.92889156  500.31285788]
[ 533.66559503  466.72652853]
[ 497.08856127  502.25842979]
[ 499.19394094  500.51721905]
[ 500.44495903  499.8238769 ]
[-758.35853776  -38.715806  ]
[ 501.98734784  498.8793409 ]
[ 497.23426097  501.95183354]
[ 500.62408025  499.03303987]
[ 503.04733496  496.71364919]
[-627.1261

[ 799.19856556  801.46821874]
[ 862.58520364  726.90190187]
[ 796.57133193  802.99501228]
[ 808.60332997  789.84796384]
[ 1069.2699397    286.30230082]
[ 806.82737211  792.8936188 ]
[ 806.16832314  793.66324161]
[ 821.92758367  778.9292696 ]
[ 767.90674421  829.66252587]
[-1095.20564052  -260.47904191]
[ 804.50655448  795.02222456]
[ 924.88841948  629.91256873]
[   -6.56632131  1112.79374542]
[ 655.59681136  922.99703003]
[ -288.43470433  1101.95108593]
[ 894.03617059  702.74189653]
[ 784.61199825  813.72964127]
[ 813.18214682  788.40942911]
[  259.93481967  1092.46305667]
[ 801.84343044  798.10068064]
[ 792.78339324  807.14822979]
[ 803.38111091  797.06648916]
[ 799.18615805  800.36956312]
[ 706.83119631  879.62577585]
[ 827.14106921  775.2129035 ]
[ 816.02333547  783.77295378]
[ 799.90572192  800.48491905]
[  295.29775571  1094.79982387]
[ 707.30326331  881.23280649]
[ 802.06442777  797.22526286]
[ 834.03465423  763.43120943]
[ 893.2690958   689.07390142]
[ 799.061571    800.16340903

In [3]:
est_pos[0]

[array([ 0.03905559,  0.0261328 ]),
 array([  94.95383972,  100.98931106]),
 array([ 158.28402006,  160.13367732]),
 array([ 278.82394669,  264.50608705]),
 array([ 340.47723257,  321.57930154]),
 array([ 402.18812159,  438.27267013]),
 array([ 518.03201178,  505.80676846]),
 array([ 560.73031303,  517.31158405]),
 array([ 656.50919063,  641.13366989]),
 array([ 694.54676172,  736.52348265]),
 array([ 0.08146116, -0.10211919]),
 array([ 97.42563082,  94.91231593]),
 array([ 171.30180938,  187.16087394]),
 array([ 246.49653651,  251.04785867]),
 array([ 337.88041443,  337.16006547]),
 array([ 400.71173302,  414.92610579]),
 array([ 447.54765649,  510.1698739 ]),
 array([ 621.36919588,  603.25657785]),
 array([ 577.95496494,  634.10576274]),
 array([ 623.28630565,  527.4114454 ]),
 array([-0.00560976,  0.06388044]),
 array([ 91.79277673,  89.47904053]),
 array([ 165.67034688,  151.32664803]),
 array([ 239.63521953,  240.77169805]),
 array([ 356.02930709,  353.67570069]),
 array([ 438.128