In [2]:
import numpy.linalg as nl
import numpy as np

import scipy.io as sio

mat_contents = sio.loadmat('system_identification_eval.mat')

x0 = mat_contents['x0']
xd0 = mat_contents['xd0']+29.0576
xdp = mat_contents['xdp']+29.0576
xp = mat_contents['xp']
xp = np.transpose(xp)
xdp = np.transpose(xdp)

In [4]:
time_interval = 1/15
def acceleration (x, xd, xp, xdp):
    return -0.01150047*x + -0.31465897 * xd + 0.01154398* xp + 0.28080008* xdp

def disp(u , t, a):
    return u*t +0.5*a *t *t

def velocity(u, t, a):
    return u + a*t
distances = list()
x = x0
distances.append(x)
xd = xd0
xdd = acceleration(x, xd, xp[0], xdp[0])

for t in range (1, 150):
    x = x + disp(xd, time_interval, xdd)
    xd = velocity(xd, time_interval, xdd)
    xdd = acceleration(x, xd, xp[t], xdp[t])
    distances.append(x)
distances


[array([[ 538.356048]]),
 array([[ 539.05760932]]),
 array([[ 539.75870074]]),
 array([[ 540.45938305]]),
 array([[ 541.15971639]]),
 array([[ 541.85975841]]),
 array([[ 542.55956272]]),
 array([[ 543.25917996]]),
 array([[ 543.95866046]]),
 array([[ 544.65805601]]),
 array([[ 545.35741938]]),
 array([[ 546.05680203]]),
 array([[ 546.7562521]]),
 array([[ 547.45581306]]),
 array([[ 548.1555244]]),
 array([[ 548.8554237]]),
 array([[ 549.55554742]]),
 array([[ 550.25592963]]),
 array([[ 550.9566017]]),
 array([[ 551.65759384]]),
 array([[ 552.35893446]]),
 array([[ 553.06064913]]),
 array([[ 553.76276122]]),
 array([[ 554.46529259]]),
 array([[ 555.16826459]]),
 array([[ 555.87169805]]),
 array([[ 556.57561296]]),
 array([[ 557.28002754]]),
 array([[ 557.98495473]]),
 array([[ 558.69040095]]),
 array([[ 559.39636751]]),
 array([[ 560.10285272]]),
 array([[ 560.80985476]]),
 array([[ 561.51737316]]),
 array([[ 562.22540721]]),
 array([[ 562.93395469]]),
 array([[ 563.64301305]]),
 array(

In [6]:
np.savetxt('submission.txt', distances, newline='\r\n')